import type { AgendaEventR3, AgendaPriorityR3 } from '../domain/agendaEventR3';
import { validateAgendaEventR3 } from '../domain/agendaEventR3';
import { addAgendaLocalDaysR3, zonedDateTimeToIsoR3 } from '../domain/agendaRecurrenceR3';

export const AGENDA_STORAGE_KEY_R3 = 'lia.os.agenda.events.v3';
export const AGENDA_LEGACY_STORAGE_KEY_V1 = 'lia.os.agenda.local.v1';
export const AGENDA_LEGACY_ACTION_QUEUE_KEY_V1 = 'lia.os.agenda.actionQueue.v1';
export const AGENDA_LEGACY_ALERTS_KEY = 'lia-agenda-alerts';
export interface StorageLikeR3 { getItem(key:string): string|null; setItem(key:string,value:string):void; removeItem(key:string):void }
export interface AgendaPersistenceEnvelopeR3 { version:3; revision:number; events:AgendaEventR3[]; savedAt:string; writerId:string }
export interface AgendaPersistenceIssueR3 { path:string; message:string }
export type AgendaPersistenceSourceR3 = 'v3'|'migrated_v1'|'seed'|'empty'|'corrupt';
export type AgendaParseResultR3 = {success:true;envelope:AgendaPersistenceEnvelopeR3;errors:AgendaPersistenceIssueR3[];warnings:AgendaPersistenceIssueR3[]} | {success:false;errors:AgendaPersistenceIssueR3[];warnings:AgendaPersistenceIssueR3[]};
export interface AgendaLoadResultR3 { source:AgendaPersistenceSourceR3; events:AgendaEventR3[]; revision:number; errors:AgendaPersistenceIssueR3[]; warnings:AgendaPersistenceIssueR3[]; envelope?:AgendaPersistenceEnvelopeR3 }
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const iso=(v:unknown):v is string=>typeof v==='string'&&Number.isFinite(Date.parse(v));
export function parseAgendaPersistenceEnvelopeR3(value:unknown):AgendaParseResultR3 {
  const errors:AgendaPersistenceIssueR3[]=[]; if(!record(value)) return {success:false,errors:[{path:'$',message:'Envelope inválido'}],warnings:[]};
  if(value.version!==3) errors.push({path:'version',message:'Debe ser 3'}); if(!Number.isInteger(value.revision)||(value.revision as number)<0) errors.push({path:'revision',message:'Revisión inválida'}); if(!iso(value.savedAt)) errors.push({path:'savedAt',message:'Fecha inválida'}); if(typeof value.writerId!=='string'||!value.writerId) errors.push({path:'writerId',message:'Writer ID obligatorio'});
  const events:AgendaEventR3[]=[]; if(!Array.isArray(value.events)) errors.push({path:'events',message:'Debe ser lista'}); else { const ids=new Set<string>(); value.events.forEach((item,i)=>{const result=validateAgendaEventR3(item);if(!result.success) result.errors.forEach(e=>errors.push({path:`events[${i}].${e.path}`,message:e.message})); else if(ids.has(result.event.id)) errors.push({path:`events[${i}].id`,message:'ID duplicado'}); else {ids.add(result.event.id);events.push(result.event);}}); }
  if(errors.length) return {success:false,errors,warnings:[]}; return {success:true,envelope:{version:3,revision:value.revision as number,events,savedAt:value.savedAt as string,writerId:value.writerId as string},errors:[],warnings:[]};
}
export function readAgendaPersistenceR3(storage:StorageLikeR3):AgendaLoadResultR3 { let raw:string|null; try{raw=storage.getItem(AGENDA_STORAGE_KEY_R3);}catch(error){return{source:'corrupt',events:[],revision:0,errors:[{path:AGENDA_STORAGE_KEY_R3,message:error instanceof Error?error.message:'Error de lectura'}],warnings:[]};} if(raw===null)return{source:'empty',events:[],revision:0,errors:[],warnings:[]}; try{const parsed=parseAgendaPersistenceEnvelopeR3(JSON.parse(raw));return parsed.success?{source:'v3',events:parsed.envelope.events,revision:parsed.envelope.revision,errors:[],warnings:parsed.warnings,envelope:parsed.envelope}:{source:'corrupt',events:[],revision:0,errors:parsed.errors,warnings:parsed.warnings};}catch{return{source:'corrupt',events:[],revision:0,errors:[{path:AGENDA_STORAGE_KEY_R3,message:'JSON corrupto'}],warnings:[]};} }
export function writeAgendaPersistenceR3(storage:StorageLikeR3,envelope:AgendaPersistenceEnvelopeR3):{success:true;envelope:AgendaPersistenceEnvelopeR3}|{success:false;errors:AgendaPersistenceIssueR3[]} { const valid=parseAgendaPersistenceEnvelopeR3(envelope);if(!valid.success)return{success:false,errors:valid.errors};try{storage.setItem(AGENDA_STORAGE_KEY_R3,JSON.stringify(valid.envelope));return{success:true,envelope:valid.envelope};}catch(error){return{success:false,errors:[{path:AGENDA_STORAGE_KEY_R3,message:error instanceof Error?error.message:'Error de escritura'}]};} }
const localIso=(dateKey:string,time:string,timezone:string):string=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(dateKey)||!/^\d{2}:\d{2}$/.test(time))throw new RangeError('Fecha u hora legada inválida');const [year,month,day]=dateKey.split('-').map(Number),[hour,minute]=time.split(':').map(Number);return zonedDateTimeToIsoR3({year,month,day,hour,minute,second:0},timezone);};
export function migrateLegacyAgendaV1R3(storage:StorageLikeR3,timezone='America/Mexico_City'):AgendaLoadResultR3 { let raw:string|null;try{raw=storage.getItem(AGENDA_LEGACY_STORAGE_KEY_V1);}catch(error){return{source:'corrupt',events:[],revision:0,errors:[{path:AGENDA_LEGACY_STORAGE_KEY_V1,message:error instanceof Error?error.message:'Error'}],warnings:[]};}if(raw===null)return{source:'empty',events:[],revision:0,errors:[],warnings:[]};let value:unknown;try{value=JSON.parse(raw);}catch{return{source:'corrupt',events:[],revision:0,errors:[{path:'$',message:'JSON v1 corrupto'}],warnings:[]};}if(!record(value)||value.version!==1||!Array.isArray(value.blocks))return{source:'corrupt',events:[],revision:0,errors:[{path:'$',message:'Estructura v1 inválida'}],warnings:[]};
  const events:AgendaEventR3[]=[],errors:AgendaPersistenceIssueR3[]=[],warnings:AgendaPersistenceIssueR3[]=[],ids=new Set<string>();
  value.blocks.forEach((item,i)=>{if(!record(item)){errors.push({path:`blocks[${i}]`,message:'Bloque inválido'});return;}const text=(k:string):string=>typeof item[k]==='string'?item[k] as string:'';const id=text('id');if(!id||ids.has(id)){errors.push({path:`blocks[${i}].id`,message:'ID ausente o duplicado'});return;}try{let start=localIso(text('dateKey'),text('start'),timezone),end=localIso(text('dateKey'),text('end'),timezone);if(Date.parse(end)===Date.parse(start)){errors.push({path:`blocks[${i}].end`,message:'Final igual al inicio'});return;}if(Date.parse(end)<Date.parse(start)){end=localIso(addAgendaLocalDaysR3(text('dateKey'),1),text('end'),timezone);warnings.push({path:`blocks[${i}].end`,message:'Cruce de medianoche interpretado'});}const location=text('location'),virtual=/remoto|virtual|videollamada|enlace/i.test(location),created=iso(item.createdAt)?item.createdAt:new Date(Date.parse(start)).toISOString();const priority:AgendaPriorityR3=item.priority==='Alta'?'high':item.priority==='Baja'?'low':'medium';const candidate:AgendaEventR3={id,title:text('title'),startTime:start,endTime:end,timezone,mode:virtual?'virtual':'in_person',...(location?{locationName:location}:{}),...(!virtual&&location?{destination:{name:location}}:{}),priority,status:'scheduled',attendees:[],responsible:{name:text('owner')},...(text('objective')?{objective:text('objective')}:{}),preparationMinutes:0,parkingMinutes:0,walkingMinutes:0,followUpRequired:false,recurrence:{frequency:'none'},createdAt:created,updatedAt:created,source:'migrated_v1'};const valid=validateAgendaEventR3(candidate);if(!valid.success)valid.errors.forEach(e=>errors.push({path:`blocks[${i}].${e.path}`,message:e.message}));else{ids.add(id);events.push(valid.event);}}catch(error){errors.push({path:`blocks[${i}]`,message:error instanceof Error?error.message:'Error de migración'});}});return{source:'migrated_v1',events,revision:0,errors,warnings}; }
export function loadAgendaPersistenceR3(storage:StorageLikeR3,seeds:readonly AgendaEventR3[]=[],timezone='America/Mexico_City'):AgendaLoadResultR3 {const v3=readAgendaPersistenceR3(storage);if(v3.source==='v3'||v3.source==='corrupt')return v3;const migrated=migrateLegacyAgendaV1R3(storage,timezone);if(migrated.source==='migrated_v1'||migrated.source==='corrupt')return migrated;if(seeds.length)return{source:'seed',events:seeds.map(e=>({...e})),revision:0,errors:[],warnings:[]};return{source:'empty',events:[],revision:0,errors:[],warnings:[]};}
export function persistMigratedAgendaR3(storage:StorageLikeR3,result:AgendaLoadResultR3,writerId:string,savedAt=new Date().toISOString()){if(result.source!=='migrated_v1')return{success:false as const,errors:[{path:'source',message:'No es una migración'}]};return writeAgendaPersistenceR3(storage,{version:3,revision:result.revision,events:result.events,savedAt,writerId});}
