import type { AgendaEventR3 } from '../domain/agendaEventR3';
import { validateAgendaEventR3 } from '../domain/agendaEventR3';
import type { AgendaPersistenceEnvelopeR3,AgendaPersistenceSourceR3,StorageLikeR3 } from './agendaPersistenceR3';
import { AGENDA_STORAGE_KEY_R3,loadAgendaPersistenceR3,parseAgendaPersistenceEnvelopeR3,writeAgendaPersistenceR3 } from './agendaPersistenceR3';
export type AgendaPersistenceStatusR3='idle'|'loading'|'ready'|'memory_only'|'error';
export interface AgendaStoreSnapshotR3 {version:3;revision:number;events:readonly AgendaEventR3[];hydrated:boolean;persistenceStatus:AgendaPersistenceStatusR3;persistenceSource:AgendaPersistenceSourceR3;warnings:readonly string[];lastPersistedAt?:string}
export interface AgendaStorageEventR3 {key:string|null;newValue:string|null}
export interface AgendaStorageEventTargetR3 {addEventListener(type:'storage',listener:(event:AgendaStorageEventR3)=>void):void;removeEventListener(type:'storage',listener:(event:AgendaStorageEventR3)=>void):void}
export interface AgendaStoreOptionsR3 {storage?:StorageLikeR3;seedEvents?:readonly AgendaEventR3[];writerId?:string;idFactory?:()=>string;now?:()=>Date;timezone?:string}
export interface AgendaStoreR3 {getSnapshot():AgendaStoreSnapshotR3;subscribe(listener:()=>void):()=>void;hydrate():AgendaStoreSnapshotR3;addEvent(event:AgendaEventR3):AgendaEventR3;updateEvent(id:string,updates:Partial<AgendaEventR3>):AgendaEventR3;upsertEvent(event:AgendaEventR3):AgendaEventR3;cancelEvent(id:string):AgendaEventR3;completeEvent(id:string):AgendaEventR3;removeEvent(id:string):boolean;resetToSeed():void;persist():boolean;connectStorageSync(target?:AgendaStorageEventTargetR3):()=>void;destroy():void}
let fallbackCounter=0;const defaultId=()=>{const cryptoApi=globalThis.crypto;if(cryptoApi&&typeof cryptoApi.randomUUID==='function')return cryptoApi.randomUUID();fallbackCounter+=1;return `agenda-${Date.now().toString(36)}-${fallbackCounter.toString(36)}-${Math.random().toString(36).slice(2)}`;};
const clone=(e:AgendaEventR3):AgendaEventR3=>({...e,attendees:e.attendees.map(a=>({...a})),responsible:{...e.responsible},...(e.destination?{destination:{...e.destination}}:{}),recurrence:e.recurrence.frequency==='none'?{frequency:'none'}:{...e.recurrence,byWeekday:e.recurrence.byWeekday?[...e.recurrence.byWeekday]:undefined,exceptions:e.recurrence.exceptions?[...e.recurrence.exceptions]:undefined}});
export function createAgendaStoreR3(options:AgendaStoreOptionsR3={}):AgendaStoreR3 {const storage=options.storage,seeds=(options.seedEvents??[]).map(clone),writerId=options.writerId??defaultId(),now=options.now??(()=>new Date());let listeners=new Set<()=>void>(),cleanup:(()=>void)|undefined;let snapshot:AgendaStoreSnapshotR3=Object.freeze({version:3,revision:0,events:Object.freeze([]),hydrated:false,persistenceStatus:'idle',persistenceSource:'empty',warnings:Object.freeze([])});
 const set=(changes:Partial<AgendaStoreSnapshotR3>,events?:AgendaEventR3[])=>{snapshot=Object.freeze({...snapshot,...changes,...(events?{events:Object.freeze(events.map(clone))}:{})});listeners.forEach(l=>l());};const mutation=(events:AgendaEventR3[])=>set({revision:snapshot.revision+1,persistenceStatus:storage?'ready':'memory_only'},events);const requireValid=(event:AgendaEventR3)=>{const v=validateAgendaEventR3(event);if(!v.success)throw new TypeError(v.errors.map(e=>`${e.path}: ${e.message}`).join('; '));return v.event;};const find=(id:string)=>{const e=snapshot.events.find(x=>x.id===id);if(!e)throw new RangeError(`Evento no encontrado: ${id}`);return e;};
 const api:AgendaStoreR3={getSnapshot:()=>snapshot,subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);},hydrate(){set({persistenceStatus:'loading'});if(!storage){set({hydrated:true,persistenceStatus:'memory_only',persistenceSource:seeds.length?'seed':'empty'},seeds);return snapshot;}const r=loadAgendaPersistenceR3(storage,seeds,options.timezone);set({hydrated:true,persistenceStatus:r.source==='corrupt'?'error':'ready',persistenceSource:r.source,revision:r.revision,warnings:r.warnings.map(w=>`${w.path}: ${w.message}`)},r.events);return snapshot;},addEvent(event){const candidate=requireValid({...event,id:event.id||options.idFactory?.()||defaultId()});if(snapshot.events.some(e=>e.id===candidate.id))throw new RangeError('ID duplicado');mutation([...snapshot.events,candidate]);return clone(candidate);},updateEvent(id,updates){const old=find(id),updated=requireValid({...old,...updates,id:old.id,createdAt:old.createdAt,updatedAt:now().toISOString()});mutation(snapshot.events.map(e=>e.id===id?updated:e));return clone(updated);},upsertEvent(event){return snapshot.events.some(e=>e.id===event.id)?api.updateEvent(event.id,event):api.addEvent(event);},cancelEvent(id){return api.updateEvent(id,{status:'cancelled'});},completeEvent(id){return api.updateEvent(id,{status:'completed'});},removeEvent(id){if(!snapshot.events.some(e=>e.id===id))return false;mutation(snapshot.events.filter(e=>e.id!==id));return true;},resetToSeed(){mutation(seeds);},persist(){if(!storage){set({persistenceStatus:'memory_only'});return false;}const savedAt=now().toISOString(),envelope:AgendaPersistenceEnvelopeR3={version:3,revision:snapshot.revision,events:snapshot.events.map(clone),savedAt,writerId};const result=writeAgendaPersistenceR3(storage,envelope);if(result.success){set({persistenceStatus:'ready',lastPersistedAt:savedAt,persistenceSource:'v3'});return true;}set({persistenceStatus:'error',warnings:Object.freeze([...snapshot.warnings,...result.errors.map(e=>`${e.path}: ${e.message}`)])});return false;},connectStorageSync(target=typeof window!=='undefined'?window:undefined){if(cleanup)return cleanup;if(!target)return()=>undefined;const listener=(event:AgendaStorageEventR3)=>{if(event.key!==AGENDA_STORAGE_KEY_R3||!event.newValue)return;try{const parsed=parseAgendaPersistenceEnvelopeR3(JSON.parse(event.newValue));if(parsed.success&&parsed.envelope.writerId!==writerId&&parsed.envelope.revision>snapshot.revision)set({revision:parsed.envelope.revision,persistenceStatus:'ready',persistenceSource:'v3',lastPersistedAt:parsed.envelope.savedAt},parsed.envelope.events);}catch{return;}};target.addEventListener('storage',listener);cleanup=()=>{target.removeEventListener('storage',listener);cleanup=undefined;};return cleanup;},destroy(){cleanup?.();listeners.clear();}};return api;}
let singleton:AgendaStoreR3|undefined;export function getAgendaStoreR3():AgendaStoreR3{singleton??=createAgendaStoreR3();return singleton;}
