import type { AgendaEventOccurrenceR3 } from '../domain/agendaRecurrenceR3';
import { expandAgendaRecurrenceR3,getAgendaDayBoundsR3,zonedDateTimeToIsoR3 } from '../domain/agendaRecurrenceR3';
import type { AgendaEventR3,AgendaTemporalStateR3 } from '../domain/agendaEventR3';
const occurrenceSort=(a:AgendaEventOccurrenceR3,b:AgendaEventOccurrenceR3)=>Date.parse(a.occurrenceStartTime)-Date.parse(b.occurrenceStartTime)||Date.parse(a.occurrenceEndTime)-Date.parse(b.occurrenceEndTime)||a.occurrenceId.localeCompare(b.occurrenceId);
const expand=(events:readonly AgendaEventR3[],start:string,end:string)=>events.flatMap(e=>expandAgendaRecurrenceR3(e,start,end)).sort(occurrenceSort);
export function getAgendaTemporalStateR3(event:Pick<AgendaEventR3,'startTime'|'endTime'>|AgendaEventOccurrenceR3,now:Date|string=new Date()):AgendaTemporalStateR3{const start='occurrenceStartTime'in event?event.occurrenceStartTime:event.startTime,end='occurrenceEndTime'in event?event.occurrenceEndTime:event.endTime,n=new Date(now).getTime();return n<Date.parse(start)?'upcoming':n<Date.parse(end)?'in_progress':'past';}
export function selectEventsForDayR3(events:readonly AgendaEventR3[],day:string,timezone:string,options:{includeCancelled?:boolean}={}):AgendaEventOccurrenceR3[]{const bounds=getAgendaDayBoundsR3(day,timezone);return expand(events,bounds.startTime,bounds.endTime).filter(o=>options.includeCancelled||o.event.status!=='cancelled');}
const mobility=(e:AgendaEventR3)=>['in_person','hybrid'].includes(e.mode)&&e.destination!==undefined&&!['cancelled','completed'].includes(e.status);
export function selectNextAgendaEventR3(events:readonly AgendaEventR3[],now:Date|string=new Date(),options:{mobilityOnly?:boolean;horizonEnd?:Date|string}={}):AgendaEventOccurrenceR3|undefined{const n=new Date(now),end=options.horizonEnd??new Date(n.getTime()+366*86400000);const eligible=expand(events,n.toISOString(),new Date(end).toISOString()).filter(o=>['scheduled','confirmed'].includes(o.event.status)&&(!options.mobilityOnly||mobility(o.event)));return eligible.find(o=>getAgendaTemporalStateR3(o,n)==='in_progress')??eligible.find(o=>Date.parse(o.occurrenceStartTime)>=n.getTime());}
export function selectUpcomingAgendaEventsR3(events:readonly AgendaEventR3[],now:Date|string,horizonEnd:Date|string,options:{limit?:number;includeCancelled?:boolean;includeCompleted?:boolean}={}):AgendaEventOccurrenceR3[]{const n=new Date(now).toISOString(),end=new Date(horizonEnd).toISOString();return expand(events,n,end).filter(o=>Date.parse(o.occurrenceStartTime)>=Date.parse(n)&&Date.parse(o.occurrenceStartTime)<Date.parse(end)&&(options.includeCancelled||o.event.status!=='cancelled')&&(options.includeCompleted||o.event.status!=='completed')).slice(0,Math.max(0,options.limit??Number.MAX_SAFE_INTEGER));}
export interface AgendaConflictR3 {firstEventId:string;secondEventId:string;overlapMinutes:number;severity:'warning'|'critical'}
export function selectAgendaConflictsR3(events:readonly AgendaEventR3[],horizonStart:Date|string,horizonEnd:Date|string,options:{includeBufferWarnings?:boolean}={}):AgendaConflictR3[]{const list=expand(events,new Date(horizonStart).toISOString(),new Date(horizonEnd).toISOString()).filter(o=>o.event.status!=='cancelled'),out:AgendaConflictR3[]=[];for(let i=0;i<list.length;i+=1)for(let j=i+1;j<list.length;j+=1){const a=list[i],b=list[j],overlap=Math.min(Date.parse(a.occurrenceEndTime),Date.parse(b.occurrenceEndTime))-Math.max(Date.parse(a.occurrenceStartTime),Date.parse(b.occurrenceStartTime));if(overlap>0)out.push({firstEventId:a.occurrenceId,secondEventId:b.occurrenceId,overlapMinutes:Math.ceil(overlap/60000),severity:'critical'});else if(options.includeBufferWarnings&&Date.parse(a.occurrenceEndTime)<=Date.parse(b.occurrenceStartTime)){const buffer=(a.event.walkingMinutes+a.event.parkingMinutes+b.event.preparationMinutes)*60000,gap=Date.parse(b.occurrenceStartTime)-Date.parse(a.occurrenceEndTime);if(gap<buffer)out.push({firstEventId:a.occurrenceId,secondEventId:b.occurrenceId,overlapMinutes:0,severity:'warning'});}}return out;}
const priorityRank={critical:4,high:3,medium:2,low:1};
export function selectAgendaPriorityEventsR3(events:readonly AgendaEventR3[],options:{includeCompleted?:boolean;limit?:number}={}):AgendaEventR3[]{return events.filter(e=>['high','critical'].includes(e.priority)&&e.status!=='cancelled'&&(options.includeCompleted||e.status!=='completed')).slice().sort((a,b)=>priorityRank[b.priority]-priorityRank[a.priority]||Date.parse(a.startTime)-Date.parse(b.startTime)||a.id.localeCompare(b.id)).slice(0,Math.max(0,options.limit??Number.MAX_SAFE_INTEGER)).map(e=>({...e}));}
export interface AgendaFreeWindowR3 {startTime:string;endTime:string;durationMinutes:number}
export function selectAgendaFreeWindowsR3(events:readonly AgendaEventR3[],input:{day:string;timezone:string;workdayStart:string;workdayEnd:string;minimumDurationMinutes:number;includeBuffers:boolean}):AgendaFreeWindowR3[]{const parse=(time:string)=>{if(!/^\d{2}:\d{2}$/.test(time))throw new RangeError('Hora inválida');const [hour,minute]=time.split(':').map(Number),[year,month,day]=input.day.split('-').map(Number);return zonedDateTimeToIsoR3({year,month,day,hour,minute,second:0},input.timezone);};const ws=Date.parse(parse(input.workdayStart)),we=Date.parse(parse(input.workdayEnd));if(we<=ws)throw new RangeError('Jornada inválida');const intervals=expand(events,new Date(ws).toISOString(),new Date(we).toISOString()).filter(o=>o.event.status!=='cancelled').map(o=>{const travel=input.includeBuffers&&['in_person','hybrid'].includes(o.event.mode)?o.event.parkingMinutes+o.event.walkingMinutes:0;return[Math.max(ws,Date.parse(o.occurrenceStartTime)-(input.includeBuffers?o.event.preparationMinutes+travel:0)*60000),Math.min(we,Date.parse(o.occurrenceEndTime))] as [number,number];}).filter(([s,e])=>e>s).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const merged:Array<[number,number]>=[];intervals.forEach(([s,e])=>{const last=merged[merged.length-1];if(last&&s<=last[1])last[1]=Math.max(last[1],e);else merged.push([s,e]);});const out:AgendaFreeWindowR3[]=[];let cursor=ws;for(const[s,e]of merged){if(s>cursor){const minutes=(s-cursor)/60000;if(minutes>=input.minimumDurationMinutes)out.push({startTime:new Date(cursor).toISOString(),endTime:new Date(s).toISOString(),durationMinutes:minutes});}cursor=Math.max(cursor,e);}if(we>cursor){const minutes=(we-cursor)/60000;if(minutes>=input.minimumDurationMinutes)out.push({startTime:new Date(cursor).toISOString(),endTime:new Date(we).toISOString(),durationMinutes:minutes});}return out;}
